### ISSUE TITLE
Issue: The underline toggle is not working as expected

### ISSUE THREAD

**Issue by leite-paulohf** [Infomaniak/swift-rich-html-editor#13]
I noticed the underline method is not working as expected when comparing with bold, italic and other styles. Once enabled, I cannot disable the underline as showed in the video link below:
https://www.loom.com/share/6886367596d945e6b14b0cd1327fac80

**Comment by valentinperignon** [comment]
Hi @leite-paulohf 
Exactly, this is an issue of WebKit, we have opened an issue 🤞 
There is a similar issue with Chrome.

**Comment by valentinperignon** [comment]
Hey @ashaTier5 

As mentioned in my previous message, this is a WebKit issue. Our editor heavily rely on the APIs provided by WebKit, so we can't fix this.
WebKit is aware of this issue and many bug reports are opened.

Here is an example of an opened bug report about this issue: https://bugs.webkit.org/show_bug.cgi?id=158115
