### ISSUE TITLE
Selected Text Not Deselected When Clicking on Empty Space

### ISSUE THREAD

**Issue by fmhayirli** [Infomaniak/swift-rich-html-editor#16]
I'm having an issue with the text editor where selected text doesn't always get deselected when I tap on an empty space. Sometimes it stays selected even after multiple taps, and the behavior seems inconsistent.

**Comment by valentinperignon** [comment]
Hello @fmhayirli 👋 
As soon as you tap an area of the editor, the focus will shift from the selected text to the tapped area.
If you tap a zone that isn't focusable (e.g., outside of the editor), the text will remain selected and retain focus. This is the system's behavior.
You should check the size of your editor and the zone you are touching.
