### ISSUE TITLE
Insert raw HTML

### ISSUE THREAD

**Issue by dharmit-livebird** [Infomaniak/swift-rich-html-editor#4]
I'm using your library to create a rich text editor. I want to implement a table insertion feature, but the library doesn't provide a direct method to inject HTML content. I've tried creating a table using simulated user actions (inserting new lines and applying formatting), but it's inefficient and doesn't produce the desired results. Can you suggest alternative approaches or workarounds to achieve this?

```swift
  private func insertTable(rows: Int, columns: Int) {
        var tableHTML = "<table border='1'>"
        for _ in 0..<rows {
            tableHTML += "<tr>"
            for _ in 0..<columns {
                tableHTML += "<td>Cell</td>"
            }
            tableHTML += "</tr>"
        }
        tableHTML += "</table>"
    }
```

**Comment by PhilippeWeidmann** [comment]
To directly modify the html you can update the property that you pass to the editor.
We recommend using SwiftSoup if you want to modify a lot of html (https://github.com/scinfu/SwiftSoup)

In this example html is modified onAppear but you can modify it from anywhere 
```swift
struct ContentView: View {
    @State private var html = ""
    @StateObject private var textAttributes = TextAttributes()

    var body: some View {
        RichHTMLEditor(html: $html, textAttributes: textAttributes)
           .onAppear { updateHTML()}
    }

    func updateHTML() {
        html = "<div>Hello world</div>"
    }
}
```
