### ISSUE TITLE
macOS: Link opening in the editor itself 

### ISSUE THREAD

**Issue by sandeep-singsys** [Infomaniak/swift-rich-html-editor#5]
I have developed a macOS application where I've integrated the link functionality using the `openLink()` function. Currently, links are opened within a WebView, but I intend to modify this behavior so that the links open in a separate browser instead.

**Comment by valentinperignon** [comment]
Hi @sandeep-singsys, thanks for your issue.
I'm not sure I understand. Could you tell me more about your problem?

**Comment by sandeep-singsys** [comment]
Hi @valentinperignon 
I have added a new link using 
`textAttributes.addLink(url: <#T##URL#>, text: <#T##String?#>)`
but when I tried to open the added link, 
It was not opening in any browser, instead it is opening within the editor view
<img width="1109" alt="Screenshot 2024-08-30 at 2 31 47 PM" src="https://github.com/user-attachments/assets/4e6762c1-9b74-4f41-8e41-c692eda93503">

**Comment by valentinperignon** [comment]
Thanks for your feedback. We will investigate and get back to you later!
