### ISSUE TITLE
Failed to resolve dependencies Dependencies could not be resolved because...

### ISSUE THREAD

**Issue by adityagi02** [Infomaniak/swift-rich-html-editor#7]
<img width="678" alt="Screenshot 2024-10-06 at 10 22 09 AM" src="https://github.com/user-attachments/assets/bf3b200e-e117-4d08-9eaa-e853861a722e">

Getting error:
`Failed to resolve dependencies Dependencies could not be resolved because 'swift-rich-html-editor' contains incompatible tools version (5.10.0) and root depends on 'swift-rich-html-editor' 1.2.0..<2.0.0.`

XCode: 15.2
though i'm running it in `macOS Sequoia`

**Comment by valentinperignon** [comment]
Hi @adityagi02,

The version of Xcode seems to be the source of the issue.
This repo uses Swift 5.10 but Xcode 15.2 is bundled with Swift 5.9.2.

Would it be possible for you to update Xcode ?
Xcode 15.3 can compile Swift 5.10.

**Comment by valentinperignon** [comment]
Unfortunately no, the only solution I see is to update Xcode to a newer version.
Xcode 15.3 or later (march 2024) is necessary.

**Comment by valentinperignon** [comment]
The package now supports swift 5.9 with the version [1.3.0](https://github.com/Infomaniak/swift-rich-html-editor/releases/tag/1.3.0).
